databases:
  - name: udonsaito_DB
    databaseName: udonsaito_db
    user: udonsaito
    region: singapore

services:
  - type: web
    name: udonsaito
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: udonsaito_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

